// pages/menu/menu.js  —  数据来源：囍er牛排馆新版菜单实物
Page({
  data: {
    categories: [
      { name: '牛排', en: 'STEAKS',     icon: '🥩' },
      { name: '前菜', en: 'STARTERS',   icon: '🦪' },
      { name: '汉堡', en: 'BURGERS',    icon: '🍔' },
      { name: '甜品', en: 'DESSERTS',   icon: '🍮' },
      { name: '酒水', en: 'DRINKS',     icon: '🍷' },
    ],
    currentCat: 0,
    currentItems: [],

    allItems: {
      // ── 0 牛排 ──────────────────────────────────────────────────────────
      0: [
        {
          id: 'st1',
          name: '美国极佳级冰鲜肋肉', en: 'USDA Prime Bone-less Rib',
          price: '¥158/100g', badge: '精选套餐',
          desc: '大理石纹丰富、多汁，荔枝木炭900°C明火炙烤，USMEF官方认证',
          img: '/images/food-steak2.jpg',
          tags: ['USDA PRIME', '荔枝木炭', '推荐'],
        },
        {
          id: 'st2',
          name: '美国极佳级冰鲜肋沙朗', en: 'USDA Prime Beef Striploin',
          price: '¥128/100g',
          desc: '纽约客经典部位，外侧脂肪炭烤后酥香，肉质紧实有嚼劲',
          img: '/images/food-steak1.jpg',
          tags: ['USDA PRIME', '荔枝木炭'],
        },
        {
          id: 'st3',
          name: '澳洲纯血M9和牛菲力', en: 'Pure Wagyu Tenderloin · Australia',
          price: '¥196/100g', badge: '顶级',
          desc: '纯血和牛里脊，几乎零筋膜，油花极细腻，入口即化',
          img: '/images/food-dish1.jpg',
          tags: ['澳洲和牛', 'M9', '荔枝木炭'],
        },
        {
          id: 'st4',
          name: '28天干式熟成肋骨肉沙朗', en: '28-Days Dry-Aged Bone-in Sirloin',
          price: '¥118/100g',
          desc: '28天干式熟成，水分浓缩，带骨炙烤后骨旁肉香最为浓烈',
          img: '/images/food-grill.jpg',
          tags: ['干式熟成', '28天', '带骨'],
        },
        {
          id: 'st5',
          name: '28天干式熟成T骨', en: '28-Days Dry-Aged T-Bone',
          price: '¥118/100g',
          desc: '一刀两吃——T骨一侧菲力一侧沙朗，分量充足适合双人分享',
          tags: ['干式熟成', '28天', '豪华'],
        },
        {
          id: 'st6',
          name: '42天波旁威士忌熟成肋骨肉', en: 'Bourbon Whisky Dry-Aged 42 Days Bone-in Rib',
          price: '¥138/100g', badge: '珍藏',
          desc: '42天波旁桶熟成，带有独特威士忌香气，风味层次最为丰富',
          tags: ['干式熟成', '42天', '威士忌'],
        },
        {
          id: 'st7',
          name: '美国国民背脊肋', en: 'US Prime Pork Ribs',
          price: '¥36/100g',
          desc: '精选猪肋骨，炭烤后焦香软嫩，性价比之选',
          tags: ['猪肋'],
        },
        {
          id: 'st8',
          name: '犹太熏制法烟熏牛肉片', en: 'Pastrami',
          price: '¥128/200g',
          desc: '传统犹太熏制工艺，黑胡椒芫荽香料腌制，薄切上桌',
          tags: ['熏制', '冷切'],
        },
        {
          id: 'st9',
          name: '鲁本三明治', en: 'Ruben Sandwich',
          price: '¥138/200g',
          img: 'cloud://cloud1-d6gc0lkxc53e45276.636c-cloud1-d6gc0lkxc53e45276-1426587167/menu/food-reuben.png',
          desc: '烟熏牛肉 + 酸菜 + 瑞士芝士 + 千岛酱，纽约经典',
          tags: ['三明治', '招牌'],
        },
        {
          id: 'st10',
          name: '炸牛骨配面包 ', en: 'Bone Marrow & Toast',
          price: '¥125',
          desc: '整根牛骨高温烤至骨髓融化，配烤面包片蘸食',
          tags: ['炭烤小菜'],
        },
        {
          id: 'st11',
          name: '炙烤极佳级牛肋条', en: 'Grilled Short Beef Rib',
          price: '¥76/2串',
          desc: '肥瘦相间，荔枝木炭明火炙烤，一口爆汁',
          tags: ['炭烤小菜', '推荐'],
        },
      ],

      // ── 1 前菜 ──────────────────────────────────────────────────────────
      1: [
        {
          id: 'ap1',
          name: '店选生蚝', en: 'Premium Oyster',
          price: '¥45/只 · 6只¥240 · 12只¥420',
          img: 'cloud://cloud1-d6gc0lkxc53e45276.636c-cloud1-d6gc0lkxc53e45276-1426587167/menu/food-oyster.jpg',
          desc: '精选时令优质生蚝，配鱼子酱与柑橘凝胶，鲜甜爽滑',
          tags: ['海鲜', '推荐'],
        },
        {
          id: 'ap2',
          name: '伊比利亚36个月火腿', en: 'Aljomar Iberico Ham 36M · 40g',
          price: '¥298',
          desc: '36个月风干伊比利亚火腿，切薄片呈盘，脂香浓郁回甘',
          tags: ['进口', '冷盘'],
        },
        {
          id: 'ap3',
          name: '招牌蟹肉饼', en: 'Crab Cake',
          price: '¥260',
          img: 'cloud://cloud1-d6gc0lkxc53e45276.636c-cloud1-d6gc0lkxc53e45276-1426587167/menu/food-tartare2.jpg',
          desc: '大量蟹肉低粉制作，外酥内嫩，配香草塔塔酱',
          tags: ['招牌', '海鲜'],
        },
        {
          id: 'ap4',
          name: '牛油果鲜虾塔塔', en: 'Avocado & Shrimp Tartare',
          price: '¥58',
          desc: '新鲜虾仁切粒，与成熟牛油果混合，清爽开胃',
          tags: ['生食'],
        },
        {
          id: 'ap5',
          name: '金枪鱼配黄油布里欧修', en: 'Tuna with Butter Brioche Tartare',
          price: '¥48',
          desc: '新鲜金枪鱼切粒，搭配自制黄油布里欧修面包',
          tags: ['海鲜', '生食'],
        },
        {
          id: 'ap6',
          name: '青苹果细叶芹鸡肉塔塔', en: 'Chicken Tartare · Green Apple & Perilla',
          price: '¥98',
          img: 'cloud://cloud1-d6gc0lkxc53e45276.636c-cloud1-d6gc0lkxc53e45276-1426587167/menu/food-tartare.jpg',
          desc: '生鸡肉切粒，配苹果粒与紫苏叶，口感清新',
          tags: ['生食', '特色'],
        },
        {
          id: 'ap7',
          name: '川味牛肉塔塔（辣）', en: 'Sichuan-Style Beef Tartare · Spicy',
          price: '¥98',
          desc: '手切新鲜牛肉，四川风格辣酱腌制，配苏打饼干',
          tags: ['生食', '辣', '特色'],
        },
        {
          id: 'ap8',
          name: '味美思虾', en: 'Shrimp Scampi',
          price: '¥88',
          desc: '大虎虾用味美思白葡萄酒、黄油、蒜蓉翻炒，香气馥郁',
          tags: ['海鲜', '推荐'],
        },
        {
          id: 'ap9',
          name: '泰香青柠虾', en: 'Thai Lemongrass Stir-fried Shrimp',
          price: '¥98',
          desc: '大虾配泰式香茅青柠汁，清爽辛香，夏日首选',
          tags: ['海鲜', '泰式'],
        },
        {
          id: 'ap10',
          name: '原切焦糖培根（片）', en: 'Sizzling Bacon-Extra Thick',
          price: '¥38/片',
          desc: '超厚切美国培根，铁板焦糖煎香，咸甜适口',
          tags: ['招牌'],
        },
        {
          id: 'ap11',
          name: '经典凯撒沙拉（培根）', en: 'Caesar Salad',
          price: '¥50',
          desc: '罗马生菜、帕玛森芝士刨片、自制凯撒汁、烟熏培根碎',
          tags: ['沙拉', '经典'],
        },
        {
          id: 'ap12',
          name: '布拉塔沙拉', en: 'Burrata Salad',
          price: '¥78',
          desc: '新鲜布拉塔芝士 + 番茄 + 罗勒油，意式简约清爽',
          tags: ['沙拉', '素食'],
        },
        {
          id: 'ap13',
          name: '羽衣甘蓝沙拉', en: 'Kale Salad',
          price: '¥55',
          desc: '新鲜羽衣甘蓝、柠檬汁按摩软化，配葵花籽与帕玛森',
          tags: ['沙拉', '素食', '健康'],
        },
        {
          id: 'ap14',
          name: '芝士烤蘑菇', en: 'Baked Mushroom',
          price: '¥25',
          desc: '新鲜蘑菇高温烤至汁水收缩，撒混合芝士拉丝',
          tags: ['蔬菜', '素食'],
        },
        {
          id: 'ap15',
          name: '清炸芦笋', en: 'Fried Asparagus',
          price: '¥45',
          desc: '新鲜芦笋裹薄浆油炸，外酥内嫩，配柠檬蛋黄酱',
          tags: ['蔬菜'],
        },
        {
          id: 'ap16',
          name: '奶油蘑菇浓汤', en: 'Cream of Mushroom Soup',
          price: '¥45',
          desc: '鲜蘑菇慢火熬制，配松露油点缀，口感丝滑醇厚',
          tags: ['汤', '素食', '推荐'],
        },
        {
          id: 'ap17',
          name: '奶油南瓜汤', en: 'Pumpkin Soup',
          price: '¥45',
          desc: '烤南瓜与淡奶油融合，甘甜暖胃，配南瓜籽',
          tags: ['汤', '素食'],
        },
      ],

      // ── 2 汉堡 ──────────────────────────────────────────────────────────
      2: [
        {
          id: 'bu1',
          name: '经典单层芝士堡', en: 'Classic Cheeseburger',
          price: '¥38', badge: '销量TOP1',
          img: 'cloud://cloud1-d6gc0lkxc53e45276.636c-cloud1-d6gc0lkxc53e45276-1426587167/menu/food-burger-classic.png',
          desc: '手打牛肉饼、美式芝士、焦糖洋葱、自制特调酱汁',
          tags: ['招牌', '推荐'],
        },
        {
          id: 'bu2',
          name: '双层芝士堡', en: 'Double Cheeseburger',
          price: '¥65',
          img: 'cloud://cloud1-d6gc0lkxc53e45276.636c-cloud1-d6gc0lkxc53e45276-1426587167/menu/food-burger-double.png',
          desc: '双层手打牛肉饼、双层芝士融化叠加，配番茄酸黄瓜',
          tags: ['豪华'],
        },
        {
          id: 'bu3',
          name: '黄油蘑菇堡', en: 'Butter Mushroom Burger',
          price: '¥48', badge: '人气爆品',
          img: 'cloud://cloud1-d6gc0lkxc53e45276.636c-cloud1-d6gc0lkxc53e45276-1426587167/menu/food-burger-mushroom.png',
          desc: '黄油炒蘑菇 + 瑞士芝士的黄金组合，汁多鲜美',
          tags: ['推荐'],
        },
        {
          id: 'bu4',
          name: '泰式菠萝堡', en: 'Thai Pineapple Burger',
          price: '¥45', badge: '销量TOP3',
          img: 'cloud://cloud1-d6gc0lkxc53e45276.636c-cloud1-d6gc0lkxc53e45276-1426587167/menu/food-burger-thai.png',
          desc: '炭烤菠萝片配泰式辣酱，酸甜辣层次丰富',
          tags: ['特色', '泰式'],
        },
        {
          id: 'bu5',
          name: '烤红椒鸡翅堡', en: 'Grilled Red Pepper Chicken Burger',
          price: '¥38',
          desc: '炭烤鸡腿肉配烤红椒，清爽不腻，轻食之选',
          tags: ['鸡肉'],
        },
        {
          id: 'bu6',
          name: '水波蛋三明治', en: 'Scrambled Egg Sandwich',
          price: '¥25',
          desc: '完美水波蛋 + 火腿 + 全麦吐司，简单扎实的早午餐',
          tags: ['早午餐'],
        },
        {
          id: 'bu7',
          name: '鲁本三明治', en: 'Ruben Sandwich',
          price: '¥138',
          img: 'cloud://cloud1-d6gc0lkxc53e45276.636c-cloud1-d6gc0lkxc53e45276-1426587167/menu/food-reuben.png',
          desc: '烟熏牛肉配酸菜、瑞士芝士、千岛酱，纽约经典款',
          tags: ['招牌', '特色'],
        },
      ],

      // ── 3 甜品 & 主食 ──────────────────────────────────────────────────
      3: [
        {
          id: 'de1',
          name: '纽约芝士蛋糕', en: 'New York Cheese Cake',
          price: '¥45',
          desc: '浓郁奶酪、饼干底层，套餐指定甜品',
          tags: ['甜品', '经典'],
        },
        {
          id: 'de2',
          name: '栗子蛋糕', en: 'Chestnut Cake',
          price: '¥50',
          desc: '秋日限定风味，栗子泥与轻盈海绵蛋糕叠合',
          tags: ['甜品', '季节'],
        },
        {
          id: 'de3',
          name: '焦糖布丁', en: 'Crème Brûlée',
          price: '¥45',
          desc: '经典法式焦糖布丁，表面喷枪烤制，敲开脆壳的仪式感',
          tags: ['甜品', '法式'],
        },
        {
          id: 'de4',
          name: '提拉米苏', en: 'Tiramisu',
          price: '¥45',
          desc: '咖啡浸透的手指饼干，马斯卡彭奶酪，可可粉收尾',
          tags: ['甜品', '意式'],
        },
        {
          id: 'de5',
          name: '海盐拿铁奶昔', en: 'Sea Salt Milkshake',
          price: '¥45（加朗姆酒+15元）',
          desc: '浓郁冰淇淋奶昔，撒海盐平衡甜度，可加朗姆酒成人版',
          tags: ['甜品饮', '奶昔'],
        },
        {
          id: 'ma1',
          name: '骨髓吐司', en: 'Bone Marrow & Toast',
          price: '¥45',
          desc: '牛骨髓烤化后涂抹于厚片吐司，配海盐与香葱',
          tags: ['主食', '招牌'],
        },
        {
          id: 'ma2',
          name: '传统肉酱意面', en: 'Tomato Bolognese Pasta',
          price: '（套餐二选一）',
          desc: '慢炖牛肉肉酱搭配Al Dente意面',
          tags: ['主食', '套餐专属'],
        },
        {
          id: 'ma3',
          name: '奶油培根面', en: 'Carbonara Bacon Pasta',
          price: '（套餐二选一）',
          desc: '经典卡波纳拉，全蛋奶油酱汁，烟熏培根粒',
          tags: ['主食', '套餐专属'],
        },
        {
          id: 'ma4',
          name: '热销套餐 SIGNATURE SET MENU', en: 'For 2 Persons',
          price: '¥999/2人',
          desc: '凯撒沙拉 + 烤红椒 + 味美思虾 + 生蚝2只 + 煎芦笋 + 黄油蘑菇 + 美国极佳级冰鲜肋沙朗 + 纽约芝士蛋糕 + 主食二选一',
          tags: ['套餐', '推荐', '2人份'],
          badge: '¥999',
        },
      ],

      // ── 4 酒水 ──────────────────────────────────────────────────────────
      4: [
        {
          id: 'dr1',
          name: '阿图斯赤霞珠红葡萄酒', en: 'Artus Cabernet Sauvignon · Chile',
          price: '¥368/瓶',
          desc: '智利精选赤霞珠，单宁饱满，黑莓与雪松香气，SEAR招牌酒',
          tags: ['红酒', '推荐', '3000积分可兑'],
        },
        {
          id: 'dr2',
          name: '奥迪莎贝安娜红葡萄酒', en: 'Audacia Danna Premium Blend · S.Africa',
          price: '¥888/瓶',
          desc: '南非89%西拉40%赤霞珠6%小维多，浓郁复杂',
          tags: ['红酒', '高端'],
        },
        {
          id: 'dr3',
          name: '世界名庄', en: 'World-Renowned Estates',
          price: '咨询店员',
          desc: '每月精选世界各大名庄酒款，请询问当日酒单',
          tags: ['红酒', '名庄'],
        },
        {
          id: 'dr4',
          name: '精酿啤酒（无规则IPA）', en: 'Unorderly IPA / Pasour Hazy 4.3%',
          price: '¥45/杯',
          desc: '自酿IPA，热带水果香气与柑橘苦感平衡，清爽顺口',
          tags: ['精酿', '啤酒'],
        },
        {
          id: 'dr5',
          name: '就喝（西打）', en: 'Just Cider 2.3%',
          price: '¥40/杯',
          desc: '低度苹果气泡酒，果香清新，不嗜酒者最佳选择',
          tags: ['精酿', '低度'],
        },
        {
          id: 'dr6',
          name: '山野溪流（油桃草莓西打）', en: 'Wild Waters Cider / Peach Strawberry 3%',
          price: '¥35/杯',
          desc: '草莓与油桃果香，酸甜怡人',
          tags: ['精酿', '果味'],
        },
        {
          id: 'dr7',
          name: '格兰威特12年', en: 'The Glenlivet 12 Years',
          price: '¥60/杯',
          desc: '苏格兰单一麦芽威士忌，蜂蜜香草与轻柔花香',
          tags: ['单杯洋酒', '威士忌'],
        },
        {
          id: 'dr8',
          name: '鸡尾酒', en: 'Cocktails',
          price: '¥65/杯',
          desc: '飞天 · 教父 · 古巴自由 · 吉祥鸡特 · 爱尔兰咖啡等，询问当日特调',
          tags: ['鸡尾酒'],
        },
        {
          id: 'dr9',
          name: '美式咖啡 / 拿铁', en: 'Café Americano / Café Latte',
          price: '¥25 / ¥28',
          desc: '每日新鲜研磨，拿铁可做冰',
          tags: ['咖啡'],
        },
        {
          id: 'dr10',
          name: '软饮', en: 'Soft Drinks',
          price: '¥15起',
          desc: '可口可乐 · 雪碧 · 橙汁 · 菠萝汁 · 蔓越莓汁 · 气泡水',
          tags: ['软饮'],
        },
      ],
    },
  },

  onLoad() {
    this.setData({ currentItems: this.data.allItems[0] });
  },

  switchCat(e) {
    const index = e.currentTarget.dataset.index;
    this.setData({
      currentCat: index,
      currentItems: this.data.allItems[index],
    });
  },
});
